name: Deploy Frontend to EC2

on:
  push:
    branches:
      - DeployTest3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Check Node.js version
        run: node -v

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        env:
          CI: ""
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/pureplate-front:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pureplate-front:latest

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/pureplate-front:latest
            docker stop pureplate-front || true
            docker rm pureplate-front || true
            docker run -d -p 80:80 --name pureplate-front ${{ secrets.DOCKER_HUB_USERNAME }}/pureplate-front:latest
          EOF
